import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import UserProvider from "@/component/UserProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} >
        <UserProvider>
            <div className="flex gap-4 justify-center py-3">
              <Link href="/" className="text-xl "> Home</Link>
              <Link href="/login" className="text-xl ">login</Link>
              <Link href="/admin" className="text-xl "> Admin </Link>
              <Link href="/user" className="text-xl "> User </Link>
              <Link href="/seller" className="text-xl "> Seller </Link>
              <Link href="/supper-admin" className="text-xl "> Supper-Admin </Link>
            </div>
            {children}
        </UserProvider>
      </body>
    </html>
  );
}
